### ISSUE TITLE
Conditional simulation

### ISSUE THREAD

**Issue by msainsburydale** [cgeoga/Vecchia.jl#10]
Hi, thanks for your work on this neat package. 

Is there any way to do conditional simulation (i.e., based on the [Gaussian conditional distribution](https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Conditional_distributions))? Specifically, simulation of the spatial process at unobserved locations conditional on the observed data and known covariance-function parameters. 

The README outlines functionality for accessing [Cholesky factors](https://github.com/cgeoga/Vecchia.jl/tree/main?tab=readme-ov-file#sparse-precision-matrix-and-reverse-cholesky-factors) using `rchol()`, which takes as input a `Vecchia.VecchiaConfig` object and a vector of covariance-function parameters. However, to obtain the conditional distribution, we need to evaluate this function with respect to unobserved locations that are not associated with any data. 

Is there any way to initialise a `Vecchia.VecchiaConfig` object using the spatial locations only? Or do you have any suggestions for other ways to obtain the conditional distribution?

Many thanks in advance for any comments you may have.

**Comment by cgeoga** [comment]
Hey, MSB! Cool to chat, and thanks for poking around the code here. 

For conditional simulation, I don't have anything  concrete implemented at the moment, no. In my own applications, I really just use the approximation to get an estimate for parameters, and then I often do something a little more ad-hoc (like conditioning on the nearest hundred or thousand neighbors and predicting like that). I know that some people do something like putting your prediction points into the Vecchia configuration and then being a little clever to get the relevant components you need for the posterior covariance matrix back out. I certainly see how to do that if you put the prediction points at the end of the ordering, which is probably desirable anyway. If that is your use-case and you are predicting at some tolerably small number of points that isn't O(n), I could certainly put something together pretty quickly that would do that.  I have never thought super hard about this in part because it scares me a little bit to take the approximation so seriously as a model, beyond just being a likelihood approximation. Like, if you did this "joint" Vecchia specification with your observed and un-observed points to predict, the (2,2) block of `inv(U*U')` (if you see what I mean) won't necessarily have marginal variances that are $$\hat{\sigma}^2$$, the thing that your MLE says is the marginal variance. But maybe these concerns are primarily because I just haven't engaged more thoughtfully with this component of the practice yet. In any case, is this thing that I'm describing implementing what you have in mind?

For the reverse Cholesky factors, you're right that the configuration really doesn't need data for that. I have thus far just been lazy and just put in a vector like `fill(NaN, length(pts))` or something. But maybe the `data` field in `VecchiaConfig` should really be a `Union{Nothing, [...]}`. I think the compiler is pretty good at handling that simple kind of composite type. If you think that is preferable, I'm certainly happy to do it. In general, the configuration format is probably a bit more complicated than it needs to be. The internal types for the points and data do need to be what they are (or would require some other bookkeeping) to handle multiple replicates and chunked prediction sets (a la Stein/Chi/Welty 2004) without any allocations in the hot loop, but you aren't the first person to mention that it isn't the most user-friendly interface. If you have any thoughts about a redesign, I'd be very happy to chat!

**Comment by cgeoga** [comment]
Awesome! I've just pushed up to the master branch with a commit that adds a baseline implementation of this routine (see source [here](https://github.com/cgeoga/Vecchia.jl/blob/main/src/predict_sim.jl), and test [here](https://github.com/cgeoga/Vecchia.jl/blob/5b4f0115bbfcb01832f747ccd9595808048622b2/test/runtests.jl#L71)). I haven't done a ton of testing on it besides that it gives the correct answers when your conditioning sets are so large that the rchol factor is dense/exact, but I would hope that that test is a good indicator that this isn't completely incorrect and should be fast with `n`. Would you be willing to kick the tires on this a little in your application by just `]add Vecchia#master`-ing? If you have any thoughts on API design, I am very open-minded! 

Unrelated: I looked into the `Union{Nothing, [...]}` thing for the data in `VecchiaConfig`, and I actually think there is unfortunately something to think about there because I put an explicit type parameter for the eltype of the data so that you could autodiff through everything with respect to data. So I might stew on that for a little bit longer....

Let me know what you think!

**Comment by msainsburydale** [comment]
Thanks a lot!

I noticed that `posterior_cov()` returns the posterior covariance matrix. This might be problematic with a moderately large number of prediction locations, since conditional simulation requires the Cholesky factor of this matrix. 

I think there is a way to do conditional simulation without first constructing the posterior covariance matrix and computing its Cholesky factor. Below is an example of how to do this in `R`:

```
simulate_conditional <- function(y, covparms, nsims = 1, m = 30, reorder = TRUE, covfun_name = "matern_isotropic") {
  
  # Spatial locations of entire grid
  y <- drop(y)  # if y is passed as a multidimensional array, drop the singleton dimensions 
  N <- nrow(y)  # assumes y is a square matrix
  locs <- as.matrix(expand.grid(seq(1, 0, length.out = N), seq(0, 1, length.out = N)))
  
  # Separate observed and missing data
  non_na_indices <- which(!is.na(y))
  na_indices <- which(is.na(y))
  y_obs <- y[non_na_indices]
  locs_obs <- locs[non_na_indices, ]
  locs_pred <- locs[na_indices, ]
  
  # Number of observed and missing locations
  n_obs <- nrow(locs_obs)
  n_pred <- nrow(locs_pred)
  
  # Determine ordering for observations and predictions
  ord_obs <- if (reorder) {
    if (n_obs < 6e4) order_maxmin(locs_obs) else sample(1:n_obs)
  } else {
    1:n_obs
  }
  
  ord_pred <- if (reorder) {
    if (n_pred < 6e4) order_maxmin(locs_pred) else sample(1:n_pred)
  } else {
    1:n_pred
  }
  
  # Reorder observations and predictions
  y_obs_ordered <- y_obs[ord_obs]
  locs_obs_ordered <- locs_obs[ord_obs, , drop = FALSE]
  locs_pred_ordered <- locs_pred[ord_pred, , drop = FALSE]
  
  # Combine all locations (observed + predicted)
  locs_all <- rbind(locs_obs_ordered, locs_pred_ordered)
  inds_obs <- 1:n_obs
  inds_pred <- (n_obs + 1):(n_obs + n_pred)
  
  # Compute nearest-neighbor array for all locations
  NNarray_all <- find_ordered_nn(locs_all, m = m, lonlat = get_linkfun(covfun_name)$lonlat)
  
  # Compute inverse Cholesky entries for all locations
  Linv_all <- vecchia_Linv(covparms, covfun_name, locs_all, NNarray_all)
  
  # Initialize array to store simulations
  y_array <- array(y, dim = c(nrow(y), ncol(y), nsims))
  na_indices_cartesian <- which(is.na(y), arr.ind = TRUE)
  
  # Simulate conditional distribution
  for (j in 1:nsims) {
    # Unconditional simulation over entire grid
    z <- L_mult(Linv_all, stats::rnorm(n_obs + n_pred), NNarray_all)
    
    # Construct residual vector for observed data
    residual <- c(y_obs_ordered + z[inds_obs], rep(0, n_pred))
    
    # Propagate residual through Linv to compute conditional adjustment
    v1 <- Linv_mult(Linv_all, residual, NNarray_all)
    v1[inds_obs] <- 0  # Zero out observed contributions
    
    # Back-transform to compute conditional simulation
    v2 <- -L_mult(Linv_all, v1, NNarray_all)
    
    # Extract conditional simulations for unobserved locations
    cond_sim <- v2[inds_pred] - z[inds_pred]
    
    # Map simulations back to their original order
    y_array[cbind(na_indices_cartesian, j = j)] <- cond_sim[ord_pred]
  }
  
  return(y_array)
}
```

Example use of this function:

```
library("GpGp")
library("fields")
covparms <- c(1, 0.3, 1, 0)                                        # covariance parameters
N <- 64                                                            # number of points in each direction
locs <- as.matrix(expand.grid((1:N)/N, (1:N)/N))                   # spatial locations
y <- matrix(fast_Gp_sim(covparms, "matern_isotropic", locs), N, N) # complete data
y[1:(N/4),] <- NA                                                  # incomplete data
z <- simulateconditional(y, covparms, nsims = 30)                  # conditionally-completed data
par(mfrow = c(1, 3))
zlim_range <- range(c(y, z[, , 1], z[, , 2]), na.rm = TRUE)
fields::image.plot(y, zlim = zlim_range, main = "Incomplete data")
fields::image.plot(z[, , 1], zlim = zlim_range, main = "Conditional simulation 1")
fields::image.plot(z[, , 2], zlim = zlim_range, main = "Conditional simulation 2")
par(mfrow = c(1, 1))
```

![conditional_sims](https://github.com/user-attachments/assets/6bbd6858-47a8-481b-ab76-9de8cd06a034)

The relevant part is the for-loop, where the conditional simulations are generated based only on products involving $L^{-1}$ or $L$, where $L$ denotes the lower Cholesky factor from all spatial locations (i.e., the observed and prediction locations). The README mentioned that `RCholesky` objects `U` have a method `U' * x`... do you know if it's possible to implement a method `U_inv' * x`, where `U_inv` is the inverse of `U`? If it is possible, then perhaps we could directly translate the function given above. 

In my application, I'm using an iterative algorithm that requires conditional simulation followed by parameter estimation.  Currently, I use `R` for conditional simulation, and `Julia` for parameter estimation. However, I thought it would be neater and perhaps more efficient to have everything done in `Julia`; it's not critical, though, so no worries if we don't manage to get an efficient conditional simulator up and running. We can also leave it on the "to-do" list for now.

**Comment by cgeoga** [comment]
Ah, okay---apologies, I don't know why I assumed you wanted the full posterior considering that the literal title of your post is conditional simulation. I'm sure we can get this up and running. I'm starting some travel now and will be pretty tied up for the next ~week. Would you mind if I circled back here in about a week?

**Comment by cgeoga** [comment]
Hey MSB---I am really bad at forcing myself to sleep on planes. So here is a quick prototype implementation of the conditional simulation. How does an interface like this work for you? 
```julia

using Vecchia, BesselK, StaticArrays, SparseArrays, NearestNeighbors

function condsim(vc::Vecchia.VecchiaConfig{H,D,F}, params,
                 pred_pts::Vector{SVector{D,Float64}};
                 ncondition=maximum(length, vc.condix)) where{H,D,F}
  # get the given data points and make a tree for fast conditioning set
  # collection.
  (n, m) = (sum(length, vc.pts), length(pred_pts))
  pts    = reduce(vcat, vc.pts)
  # create the new conditioning set elements for the joint configuration of
  # given and prediction points.
  jcondix = copy(vc.condix)
  sizehint!(jcondix, length(vc.condix) + length(pred_pts)) # could also pre-allocate
  for k in eachindex(pred_pts)
    tree       = KDTree(vcat(pts, pred_pts[1:(k-1)]))
    k_cond_ixs = NearestNeighbors.knn(tree, pred_pts[k], min(ncondition, n+(k-1)))[1]
    sort!(k_cond_ixs)
    push!(jcondix, k_cond_ixs)
  end
  # create the augmented/joint point list (for now, just singleton predictions):
  jpts  = vcat(vc.pts, [[x] for x in pred_pts])
  # create the final joint config object. The data being passed in here isn't a
  # compliant size, but we'll never touch it.
  jcfg  = Vecchia.VecchiaConfig(vc.kernel, [hcat(NaN) for _ in eachindex(jpts)], 
                                jpts, jcondix)
  Us    = sparse(Vecchia.rchol(jcfg, params))
  Usnn  = Us[1:n, 1:n]
  # conditional simulation using standard tricks with Cholesky factors:
  data  = reduce(vcat, vc.data)
  rawwn = randn(length(pred_pts), size(data, 2))
  jwn   = vcat(Usnn'*data, rawwn)
  (Us'\jwn
end


# test:
grid1d   = range(0.0, 1.0, length=42)
ptsm     = [SA[x...] for x in Iterators.product(grid1d, grid1d)]
pts_have = vec(ptsm[:,10:end])
pts_pred = vec(ptsm[:,1:9])

Sig      = [matern(x, y, (1.0, 0.5, 0.85)) for x in pts_have, y in pts_have]
sim      = cholesky(Sig).L*randn(length(pts_have))

cfg      = Vecchia.nosortknnconfig(sim, pts_have, 10, matern)
test     = condsim(cfg, [1.0, 0.5, 0.85], pts_pred)

tt       = reshape(test, (42, 9))
ss       = reshape(sim,  (42, 42-9))
gheatmap(hcat(tt, ss))
```

This wifi is terrible so I probably won't try to do any pushing or development on the actual Julia package, but maybe this is enough to play around and see what other changes you'd like. I think the biggest performance bottleneck right now is rebuilding the tree for every prediction point. There is an adaptive KD tree package that I have seen before, but it will need a PR to accept a `Vector{SVector{D, Float64}}` instead of a `Matrix{Float64}`. I haven't played with the performance of that code, but assuming it is workable I think the only other potentially appealing optimizations would be squeezing out allocations and using views in a few places and stuff, which is all very routine and easy to set up.

Let me know if there is some other API/return value/whatever else that would better suit your use-case!

**Comment by msainsburydale** [comment]
Hi Chris, sorry for the delayed reply, a few work things came up in the last week that had to get done before Christmas!

Thanks for prototyping the conditional simulation, this is great! I added some functionality for simulating multiple realisations, please see code below. 

There seems to be some incongruence between the conditional simulations and the observed data (please see plots below). Do you think this is just an issue with how the simulations and observed data are recombined? 

```julia
using Vecchia, BesselK, StaticArrays, SparseArrays, NearestNeighbors, LinearAlgebra, Plots

function condsim(vc::Vecchia.VecchiaConfig{H,D,F}, params,
    pred_pts::Vector{SVector{D,Float64}};
    ncondition=maximum(length, vc.condix),
    nsims::Int=1) where {H,D,F}
    # get the given data points and make a tree for fast conditioning set
    # collection.
    (n, m) = (sum(length, vc.pts), length(pred_pts))
    pts    = reduce(vcat, vc.pts)  # Flatten the given points

    # create the new conditioning set elements for the joint configuration of
    # given and prediction points.
    jcondix = copy(vc.condix)
    sizehint!(jcondix, length(vc.condix) + m) # could also pre-allocate

    for k in 1:m
        tree = KDTree(vcat(pts, pred_pts[1:(k-1)]))  # Include preceding prediction points
        k_cond_ixs = NearestNeighbors.knn(tree, pred_pts[k], min(ncondition, n + k - 1))[1]
        sort!(k_cond_ixs)
        push!(jcondix, k_cond_ixs)
    end

    # create the augmented/joint point list.
    jpts = vcat(vc.pts, [[x] for x in pred_pts])

    # create the final joint config object. The data being passed in here isn't a
    # compliant size, but we'll never touch it.
    jcfg = Vecchia.VecchiaConfig(vc.kernel, [hcat(NaN) for _ in eachindex(jpts)], 
                    jpts, jcondix)

    # Compute the Cholesky factor for the joint configuration
    Us = sparse(Vecchia.rchol(jcfg, params))
    Usnn = Us[1:n, 1:n]  # Sub-matrix for given points

    # Prepare storage for simulations
    data = reduce(vcat, vc.data)  # Combine observed data
    sim_results = Matrix{eltype(data)}(undef, m, nsims)

    # Generate multiple simulations
    for i in 1:nsims
        rawwn = randn(m, size(data, 2))  # Random noise for prediction points
        jwn = vcat(Usnn' * data, rawwn)  # Combine with observed data
        sim_result = Us' \ jwn  # Solve for simulation
        sim_results[:, i] = sim_result[n+1:end, :]  # Extract simulation for prediction points
    end

    sim_results  # Return as a matrix with `m` rows and `nsims` columns
end

# Test setup: 
n = 64
grid1d    = range(0.0, 1.0, length=n)
ptsm      = [SA[x...] for x in Iterators.product(grid1d, grid1d)]
pts_have  = vec(ptsm[:,10:end])
pts_pred  = vec(ptsm[:,1:9])
covparams = [1.0, 0.5, 0.85] 
Sig       = [matern(x, y, covparams) for x in pts_have, y in pts_have]
sim       = cholesky(Sig).L*randn(length(pts_have))
cfg       = Vecchia.nosortknnconfig(sim, pts_have, 10, matern)

# Test with 1 simulation:
test     = condsim(cfg, covparams, pts_pred, nsims = 1)
tt       = reshape(test, n, :)
ss       = reshape(sim,  n, :)
heatmap(hcat(tt, ss), title="Conditional Simulation 1")

# Test with multiple replicates:
test     = condsim(cfg, covparams, pts_pred, nsims = 3)
dat  = hcat(fill(missing, n, n - size(ss, 2)), ss)
tt1  = hcat(reshape(test[:, 1], n, :), ss)
tt2  = hcat(reshape(test[:, 2], n, :), ss)
tt3  = hcat(reshape(test[:, 3], n, :), ss)
hm1 = heatmap(dat, title = "Incomplete data")
hm2 = heatmap(tt1, title = "Conditional simulation 1")
hm3 = heatmap(tt2, title = "Conditional simulation 2")
hm4 = heatmap(tt3, title = "Conditional simulation 3")
plot(hm1, hm2, hm3, hm4)
``` 

<img width="883" alt="Vecchiajl_conditional_sims" src="https://github.com/user-attachments/assets/89283e5f-85b8-43f9-9f9a-c3e504fbfa2f" />

**Comment by cgeoga** [comment]
Hey MSB---thanks for taking a look at this. I did a little tinkering and can reproduce what you see. I'm not in a spot where I can do a pen-and-paper check, but I do think the simulation mechanism is correct. What I think is going on is that the conditioning point size and ordering is probably pretty relevant here. I used my own version of the code to get multiple simulations (using the lazy trick of giving data as `reduce(hcat, fill(sim, n_replicates)))` to the `VecchiaConfig`) like this:
```julia

include("condsim.jl") # removed demo from that file

# quick anisotropy:
@inline function aniso_L()
  theta = pi/3
  Lam   = @SMatrix [3.0 0.0
                    0.0 0.5]
  R     = @SMatrix [cos(theta) -sin(theta)
                    sin(theta)  cos(theta)]
  cholesky(R*Lam*R').L
end

# Aside: still no heap allocations. Julia is pretty cool.
function matern_aniso(x, y, params)
  L  = aniso_L()
  matern(L*x, L*y, params)
end

grid1d   = range(0.0, 1.0, length=42)
ptsm     = [SA[x...] for x in Iterators.product(grid1d, grid1d)]
pts_have = vec(ptsm[:,10:end])
pts_pred = vec(ptsm[:,1:9])
pts_tot  = vcat(pts_have, pts_pred)

params   = [1.0, 0.15, 1.85]

# Do a full simulation for a sanity check:
Sig      = [matern_aniso(x, y, params) for x in pts_tot, y in pts_tot]
sim_tot  = cholesky(Sig).L*randn(length(pts_tot))
sim      = sim_tot[1:length(pts_have)]

sim_rep  = reduce(hcat, fill(sim, 10))
cfg      = Vecchia.nosortknnconfig(sim_rep, pts_have, 30, matern_aniso)

(;sims, joint_rchol) = condsim(cfg, params, pts_pred)

println()
println("Actual joint simulation from Vecchia rchol: ")

rchol_sim = joint_rchol'\randn(length(sim_tot))
fs1 = reshape(rchol_sim[1:length(pts_have)], (42, 42-9))
fs2 = reshape(rchol_sim[(length(pts_have)+1):end], (42, 9))
fs  = hcat(fs2, fs1)
gheatmap(reshape(fs, (42,42)), x=grid1d, y=grid1d)
println()
println()

println()
println("Actual joint simulation, showing conditioning data: ")

fs1 = reshape(sim_tot[1:length(pts_have)], (42, 42-9))
fs2 = reshape(sim_tot[(length(pts_have)+1):end], (42, 9))
fs  = hcat(fs2, fs1)
gheatmap(fs, x=grid1d, y=grid1d)
println()
println()


println("**Conditional simulations for the first 9 columns**")
for j in 1:size(sims, 2)
  println()
  tt       = reshape(sims[:,j], (42, 9))
  ss       = reshape(sim,  (42, 42-9))
  gheatmap(hcat(tt, ss), x=grid1d, y=grid1d)
  println()
end
```
I added a strong geometric anisotropy to the kernel that would make it easier to see weird artifacts. Sorry about the plotting stuff---I am on Linux with Wayland, and I just cannot get Plots.jl to actually give me a plot. I kind of rage quit all of the Julia plot ecosystems years ago and now just use my own thin wrapper of gnuplot that outputs sixel images which I can view right in my terminal (which is nice when you spend so much time in an ssh session anyway). But if you tweak the heatmap line, you should be able to run this yourself.

The main takeaway is that I think you'll probably want to design the configuration more thoughtfully than my current draft of the code does (note that the prediction points are basically coordinate-ordered---maybe randomizing would be useful?), and also crank up the number of conditioning points. In `GpGp`, a quick look at `help(fast_Gp_sim)` or whatever the function is called looks like they default to `m=30` conditioning points, which makes sense. Maybe try this and play a little with conditioning design/size and let me know what you think?

**Comment by msainsburydale** [comment]
Thanks a lot for taking another look at this. I think you're probably right that the ordering and number of conditioning points matters here. 

I'm out of time on this current project, so I'll have to leave the investigations there and stick with my current R implementation for the time being. I'll let you know if I do some further experimenting with the ordering and number of conditioning points at some point down the road.

**Comment by cgeoga** [comment]
Hey MSB---that all makes sense. I think Joe has probably thought about that implementation a lot and it is a good idea to stick with it, at least for now. I'm sure some day somebody in the field will want to do something that requires writing and hacking on a weird kernel, in which case they'll have to use Julia, and maybe we can convince them to spend the time working on that here. Maybe it will be one of us! But I'm sure this functionality will get dialed in here as well at some point. 

I think for now I'll commit up this very simple version that has no guardrails and tag a new release. 

Let's stay in touch! I'm sure we'll be seeing plenty of each other in the coming years.
